import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./i18n/request.js');

/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [

      // ─── Old WordPress EN → new slugs ──────────────────────────────────────
      { source: '/services/real-estate-in-panama-panama-contact-services-assists-you', destination: '/services/buy-property-panama-foreigners', permanent: true },
      { source: '/services/real-estate-in-panama-panama-contact-services-assists-you/', destination: '/services/buy-property-panama-foreigners', permanent: true },
      { source: '/services/drivers-license-for-foreigners-in-panama-what-you-need-to-know', destination: '/services/drivers-license-panama-foreigners', permanent: true },
      { source: '/services/drivers-license-for-foreigners-in-panama-what-you-need-to-know/', destination: '/services/drivers-license-panama-foreigners', permanent: true },
      { source: '/services/importing-goods-and-merchandise-in-panama', destination: '/services/import-goods-to-panama', permanent: true },
      { source: '/services/importing-goods-and-merchandise-in-panama/', destination: '/services/import-goods-to-panama', permanent: true },
      { source: '/services/setting-up-a-business-in-panama-steps-and-recommendations', destination: '/services/company-formation-panama-foreigners', permanent: true },
      { source: '/services/setting-up-a-business-in-panama-steps-and-recommendations/', destination: '/services/company-formation-panama-foreigners', permanent: true },
      { source: '/services/qualified-investor-visa-in-panama-three-possible-optionss', destination: '/services/qualified-investor-residency-panama', permanent: true },
      { source: '/services/qualified-investor-visa-in-panama-three-possible-optionss/', destination: '/services/qualified-investor-residency-panama', permanent: true },
      { source: '/services/the-panamanian-insurance-system-a-detailed-approach-for-the-novice', destination: '/services/health-insurance-expats-panama', permanent: true },
      { source: '/services/the-panamanian-insurance-system-a-detailed-approach-for-the-novice/', destination: '/services/health-insurance-expats-panama', permanent: true },
      { source: '/services/friendly-nations-visa-in-panama-how-to-obtain-it', destination: '/services/friendly-nations-visa-panama-residency', permanent: true },
      { source: '/services/friendly-nations-visa-in-panama-how-to-obtain-it/', destination: '/services/friendly-nations-visa-panama-residency', permanent: true },
      { source: '/services/opening-personal-and-corporate-bank-accounts-in-panama', destination: '/services/open-bank-account-panama-foreigner', permanent: true },
      { source: '/services/opening-personal-and-corporate-bank-accounts-in-panama/', destination: '/services/open-bank-account-panama-foreigner', permanent: true },
      { source: '/services/digital-nomad-visa-come-to-telework-in-panama', destination: '/services/digital-nomad-visa-panama', permanent: true },
      { source: '/services/digital-nomad-visa-come-to-telework-in-panama/', destination: '/services/digital-nomad-visa-panama', permanent: true },
      { source: '/services/retiring-in-panama-obtaining-your-retiree-visa', destination: '/services/retire-in-panama-pensionado-visa', permanent: true },
      { source: '/services/retiring-in-panama-obtaining-your-retiree-visa/', destination: '/services/retire-in-panama-pensionado-visa', permanent: true },
      { source: '/services/income-tax-declaration-in-panama', destination: '/services/panama-income-tax-declaration-foreigners', permanent: true },
      { source: '/services/income-tax-declaration-in-panama/', destination: '/services/panama-income-tax-declaration-foreigners', permanent: true },
      { source: '/services/programmes-speciaux-et-autres-voies-pour-devenir-resident-du-panama', destination: '/services', permanent: true },
      { source: '/services/programmes-speciaux-et-autres-voies-pour-devenir-resident-du-panama/', destination: '/services', permanent: true },
      { source: '/why-panama/quality-of-life', destination: '/why-panama/cost-of-living-quality-life-panama', permanent: true },
      { source: '/why-panama/quality-of-life/', destination: '/why-panama/cost-of-living-quality-life-panama', permanent: true },
      { source: '/why-panama/healthcare-system', destination: '/why-panama/healthcare-panama-expats', permanent: true },
      { source: '/why-panama/healthcare-system/', destination: '/why-panama/healthcare-panama-expats', permanent: true },
      { source: '/why-panama/moderate-tax-pressure', destination: '/why-panama/panama-territorial-tax-expats', permanent: true },
      { source: '/why-panama/moderate-tax-pressure/', destination: '/why-panama/panama-territorial-tax-expats', permanent: true },
      { source: '/why-panama/investment-opportunities', destination: '/why-panama/investment-opportunities-panama', permanent: true },
      { source: '/why-panama/investment-opportunities/', destination: '/why-panama/investment-opportunities-panama', permanent: true },
      { source: '/why-panama/international-financial-hub', destination: '/why-panama/panama-banking-financial-hub', permanent: true },
      { source: '/why-panama/international-financial-hub/', destination: '/why-panama/panama-banking-financial-hub', permanent: true },
      { source: '/our-services', destination: '/services', permanent: true },
      { source: '/our-services/', destination: '/services', permanent: true },
      { source: '/service_category/first-steps', destination: '/services', permanent: true },
      { source: '/service_category/first-steps/', destination: '/services', permanent: true },
      { source: '/terms-conditions', destination: '/', permanent: true },
      { source: '/terms-conditions/', destination: '/', permanent: true },
      { source: '/send-mail', destination: '/contact', permanent: true },

      // ─── Old WordPress FR → new slugs ──────────────────────────────────────
      { source: '/fr/services/le-systeme-dassurances-panameen-une-approche-detaillee-pour-le-novice', destination: '/fr/services/assurance-sante-expatries-panama', permanent: true },
      { source: '/fr/services/le-systeme-dassurances-panameen-une-approche-detaillee-pour-le-novice/', destination: '/fr/services/assurance-sante-expatries-panama', permanent: true },
      { source: '/fr/services/creation-dune-entreprise-au-panama-etapes-et-recommandations', destination: '/fr/services/creation-entreprise-panama-etrangers', permanent: true },
      { source: '/fr/services/creation-dune-entreprise-au-panama-etapes-et-recommandations/', destination: '/fr/services/creation-entreprise-panama-etrangers', permanent: true },
      { source: '/fr/services/visa-investisseur-qualifie-au-panama-trois-options-possibles', destination: '/fr/services/residence-investisseur-qualifie-panama', permanent: true },
      { source: '/fr/services/visa-investisseur-qualifie-au-panama-trois-options-possibles/', destination: '/fr/services/residence-investisseur-qualifie-panama', permanent: true },
      { source: '/fr/services/visa-pour-les-pays-amis-du-panama-comment-lobtenir', destination: '/fr/services/visa-pays-amis-panama-residence-permanente', permanent: true },
      { source: '/fr/services/visa-pour-les-pays-amis-du-panama-comment-lobtenir/', destination: '/fr/services/visa-pays-amis-panama-residence-permanente', permanent: true },
      { source: '/fr/services/permis-de-conduire-pour-les-etrangers-au-panama-ce-que-vous-devez-savoir', destination: '/fr/services/permis-conduire-panama-etrangers', permanent: true },
      { source: '/fr/services/permis-de-conduire-pour-les-etrangers-au-panama-ce-que-vous-devez-savoir/', destination: '/fr/services/permis-conduire-panama-etrangers', permanent: true },
      { source: '/fr/services/immobilier-au-panama-panama-contact-services-vous-accompagne', destination: '/fr/services/acheter-immobilier-panama-etrangers', permanent: true },
      { source: '/fr/services/immobilier-au-panama-panama-contact-services-vous-accompagne/', destination: '/fr/services/acheter-immobilier-panama-etrangers', permanent: true },
      { source: '/fr/services/ouverture-de-comptes-bancaires-personnels-et-corporatifs-au-panama', destination: '/fr/services/ouvrir-compte-bancaire-panama-non-resident', permanent: true },
      { source: '/fr/services/ouverture-de-comptes-bancaires-personnels-et-corporatifs-au-panama/', destination: '/fr/services/ouvrir-compte-bancaire-panama-non-resident', permanent: true },
      { source: '/fr/services/visa-de-nomade-numerique-venez-teletravailler-au-panama', destination: '/fr/services/visa-nomade-numerique-panama', permanent: true },
      { source: '/fr/services/visa-de-nomade-numerique-venez-teletravailler-au-panama/', destination: '/fr/services/visa-nomade-numerique-panama', permanent: true },
      { source: '/fr/services/prendre-sa-retraite-au-panama-obtenir-son-visa-de-retraite', destination: '/fr/services/retraite-au-panama-visa-pensionado', permanent: true },
      { source: '/fr/services/prendre-sa-retraite-au-panama-obtenir-son-visa-de-retraite/', destination: '/fr/services/retraite-au-panama-visa-pensionado', permanent: true },
      { source: '/fr/services/importation-de-biens-et-de-marchandises-au-panama', destination: '/fr/services/importation-marchandises-panama', permanent: true },
      { source: '/fr/services/importation-de-biens-et-de-marchandises-au-panama/', destination: '/fr/services/importation-marchandises-panama', permanent: true },
      { source: '/fr/services/declaration-de-limpot-sur-le-revenu-au-panama', destination: '/fr/services/declaration-impots-revenus-panama-expatries', permanent: true },
      { source: '/fr/services/declaration-de-limpot-sur-le-revenu-au-panama/', destination: '/fr/services/declaration-impots-revenus-panama-expatries', permanent: true },
      { source: '/fr/pourquoi-le-panama', destination: '/fr/pourquoi-s-installer-au-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/', destination: '/fr/pourquoi-s-installer-au-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/qualite-de-vie', destination: '/fr/pourquoi-panama/cout-vie-qualite-de-vie-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/qualite-de-vie/', destination: '/fr/pourquoi-panama/cout-vie-qualite-de-vie-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/systeme-de-sante', destination: '/fr/pourquoi-panama/sante-cout-expatries-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/systeme-de-sante/', destination: '/fr/pourquoi-panama/sante-cout-expatries-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/stabilite-economique', destination: '/fr/pourquoi-panama/stabilite-economique-croissance-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/stabilite-economique/', destination: '/fr/pourquoi-panama/stabilite-economique-croissance-panama', permanent: true },
      { source: '/fr/pourquoi-le-panama/place-financiere-internationale', destination: '/fr/pourquoi-panama/panama-centre-bancaire-financier', permanent: true },
      { source: '/fr/pourquoi-le-panama/place-financiere-internationale/', destination: '/fr/pourquoi-panama/panama-centre-bancaire-financier', permanent: true },
      { source: '/fr/pourquoi-le-panama/faible-pression-fiscale', destination: '/fr/pourquoi-panama/fiscalite-territoriale-panama-expatries', permanent: true },
      { source: '/fr/pourquoi-le-panama/faible-pression-fiscale/', destination: '/fr/pourquoi-panama/fiscalite-territoriale-panama-expatries', permanent: true },
      { source: '/fr/termes-et-conditions', destination: '/fr', permanent: true },
      { source: '/fr/termes-et-conditions/', destination: '/fr', permanent: true },

      // ─── Current slugs → new SEO slugs (EN) ────────────────────────────────
      { source: '/services/friendly-nations-visa-panama',     destination: '/services/friendly-nations-visa-panama-residency',         permanent: true },
      { source: '/services/qualified-investor-visa-panama',   destination: '/services/qualified-investor-residency-panama',            permanent: true },
      { source: '/services/income-tax-panama',                destination: '/services/panama-income-tax-declaration-foreigners',       permanent: true },
      { source: '/services/buy-property-in-panama',           destination: '/services/buy-property-panama-foreigners',                 permanent: true },
      { source: '/services/open-bank-account-panama',         destination: '/services/open-bank-account-panama-foreigner',             permanent: true },
      { source: '/services/start-business-in-panama',         destination: '/services/company-formation-panama-foreigners',           permanent: true },
      { source: '/services/drivers-license-panama',           destination: '/services/drivers-license-panama-foreigners',             permanent: true },
      { source: '/services/expat-insurance-panama',           destination: '/services/health-insurance-expats-panama',                permanent: true },
      { source: '/why-panama/quality-of-life-panama',         destination: '/why-panama/cost-of-living-quality-life-panama',          permanent: true },
      { source: '/why-panama/healthcare-system-panama',       destination: '/why-panama/healthcare-panama-expats',                    permanent: true },
      { source: '/why-panama/expat-community-panama',         destination: '/why-panama/investment-opportunities-panama',             permanent: true },
      { source: '/why-panama/financial-hub-latin-america',    destination: '/why-panama/panama-banking-financial-hub',                permanent: true },
      { source: '/why-panama/low-taxes-living-in-panama',     destination: '/why-panama/panama-territorial-tax-expats',              permanent: true },
      // ─── Current slugs → new SEO slugs (FR) ────────────────────────────────
      { source: '/fr/services/visa-nations-amies-panama',              destination: '/fr/services/visa-pays-amis-panama-residence-permanente',   permanent: true },
      { source: '/fr/services/visa-pays-amis-panama',                  destination: '/fr/services/visa-pays-amis-panama-residence-permanente',   permanent: true },
      { source: '/fr/services/visa-investisseur-qualifie-panama',      destination: '/fr/services/residence-investisseur-qualifie-panama',       permanent: true },
      { source: '/fr/services/impots-revenu-panama',                   destination: '/fr/services/declaration-impots-revenus-panama-expatries',  permanent: true },
      { source: '/fr/services/acheter-immobilier-au-panama',           destination: '/fr/services/acheter-immobilier-panama-etrangers',          permanent: true },
      { source: '/fr/services/ouvrir-compte-bancaire-panama',          destination: '/fr/services/ouvrir-compte-bancaire-panama-non-resident',   permanent: true },
      { source: '/fr/services/creer-entreprise-au-panama',             destination: '/fr/services/creation-entreprise-panama-etrangers',        permanent: true },
      { source: '/fr/services/permis-conduire-panama',                 destination: '/fr/services/permis-conduire-panama-etrangers',            permanent: true },
      { source: '/fr/services/assurances-expatries-panama',            destination: '/fr/services/assurance-sante-expatries-panama',            permanent: true },
      { source: '/fr/pourquoi-panama/qualite-de-vie-au-panama',        destination: '/fr/pourquoi-panama/cout-vie-qualite-de-vie-panama',       permanent: true },
      { source: '/fr/pourquoi-panama/systeme-sante-panama',            destination: '/fr/pourquoi-panama/sante-cout-expatries-panama',         permanent: true },
      { source: '/fr/pourquoi-panama/stabilite-economique-panama',     destination: '/fr/pourquoi-panama/stabilite-economique-croissance-panama', permanent: true },
      { source: '/fr/pourquoi-panama/expatries-au-panama',             destination: '/fr/pourquoi-panama/opportunites-investissement-panama',   permanent: true },
      { source: '/fr/pourquoi-panama/hub-financier-amerique-latine',   destination: '/fr/pourquoi-panama/panama-centre-bancaire-financier',     permanent: true },
      { source: '/fr/pourquoi-panama/faible-imposition-au-panama',     destination: '/fr/pourquoi-panama/fiscalite-territoriale-panama-expatries', permanent: true },

      // ─── Current slugs → new SEO slugs (ES) ────────────────────────────────
      { source: '/es/servicios/visa-naciones-amigas-panama',           destination: '/es/servicios/visa-paises-amigos-panama-residencia',       permanent: true },
      { source: '/es/servicios/visa-paises-amigas-panama',             destination: '/es/servicios/visa-paises-amigos-panama-residencia',       permanent: true },
      { source: '/es/servicios/visa-inversor-calificado-panama',       destination: '/es/servicios/residencia-inversor-calificado-panama',      permanent: true },
      { source: '/es/servicios/impuestos-renta-panama',                destination: '/es/servicios/declaracion-renta-panama-extranjeros',       permanent: true },
      { source: '/es/servicios/comprar-propiedad-en-panama',           destination: '/es/servicios/comprar-propiedad-panama-extranjeros',       permanent: true },
      { source: '/es/servicios/abrir-cuenta-bancaria-panama',          destination: '/es/servicios/abrir-cuenta-bancaria-panama-extranjero',    permanent: true },
      { source: '/es/servicios/crear-empresa-en-panama',               destination: '/es/servicios/crear-empresa-panama-extranjeros',          permanent: true },
      { source: '/es/servicios/licencia-conducir-panama',              destination: '/es/servicios/licencia-conducir-panama-extranjeros',       permanent: true },
      { source: '/es/servicios/seguros-expatriados-panama',            destination: '/es/servicios/seguro-salud-expatriados-panama',           permanent: true },
      { source: '/es/por-que-panama/calidad-de-vida-en-panama',        destination: '/es/por-que-panama/costo-vida-calidad-vida-panama',       permanent: true },
      { source: '/es/por-que-panama/sistema-salud-panama',             destination: '/es/por-que-panama/salud-costo-expatriados-panama',       permanent: true },
      { source: '/es/por-que-panama/estabilidad-economica-panama',     destination: '/es/por-que-panama/estabilidad-economica-crecimiento-panama', permanent: true },
      { source: '/es/por-que-panama/expatriados-en-panama',            destination: '/es/por-que-panama/oportunidades-inversion-panama',       permanent: true },
      { source: '/es/por-que-panama/hub-financiero-latinoamerica',     destination: '/es/por-que-panama/panama-hub-financiero-bancario',       permanent: true },
      { source: '/es/por-que-panama/baja-carga-fiscal-panama',         destination: '/es/por-que-panama/sistema-fiscal-territorial-panama',    permanent: true },

      // ─── Current slugs → new SEO slugs (PT) ────────────────────────────────
      { source: '/pt/servicos/visto-nacoes-amigas-panama',             destination: '/pt/servicos/visto-paises-amigos-panama-residencia',      permanent: true },
      { source: '/pt/servicos/visto-paises-amigas-panama',             destination: '/pt/servicos/visto-paises-amigos-panama-residencia',      permanent: true },
      { source: '/pt/servicos/visto-investidor-qualificado-panama',    destination: '/pt/servicos/residencia-investidor-qualificado-panama',   permanent: true },
      { source: '/pt/servicos/imposto-de-renda-panama',                destination: '/pt/servicos/declaracao-imposto-renda-panama-expatriados', permanent: true },
      { source: '/pt/servicos/comprar-imoveis-no-panama',              destination: '/pt/servicos/comprar-imoveis-panama-estrangeiros',        permanent: true },
      { source: '/pt/servicos/abrir-conta-bancaria-no-panama',         destination: '/pt/servicos/abrir-conta-bancaria-panama-estrangeiro',    permanent: true },
      { source: '/pt/servicos/abrir-empresa-no-panama',                destination: '/pt/servicos/abrir-empresa-panama-estrangeiros',          permanent: true },
      { source: '/pt/servicos/carteira-motorista-panama',              destination: '/pt/servicos/carteira-motorista-panama-estrangeiros',     permanent: true },
      { source: '/pt/servicos/seguros-expatriados-panama',             destination: '/pt/servicos/seguro-saude-expatriados-panama',           permanent: true },
      { source: '/pt/por-que-panama/qualidade-de-vida-no-panama',      destination: '/pt/por-que-panama/custo-vida-qualidade-vida-panama',    permanent: true },
      { source: '/pt/por-que-panama/sistema-saude-panama',             destination: '/pt/por-que-panama/saude-custo-expatriados-panama',      permanent: true },
      { source: '/pt/por-que-panama/estabilidade-economica-panama',    destination: '/pt/por-que-panama/estabilidade-economica-crescimento-panama', permanent: true },
      { source: '/pt/por-que-panama/expatriados-no-panama',            destination: '/pt/por-que-panama/oportunidades-investimento-panama',   permanent: true },
      { source: '/pt/por-que-panama/hub-financeiro-america-latina',    destination: '/pt/por-que-panama/panama-hub-financeiro-bancario',      permanent: true },
      { source: '/pt/por-que-panama/baixa-tributacao-no-panama',       destination: '/pt/por-que-panama/sistema-fiscal-territorial-panama',   permanent: true },

      // ─── Current slugs → new SEO slugs (DE) ────────────────────────────────
      { source: '/de/dienstleistungen/friendly-nations-visum-panama',             destination: '/de/dienstleistungen/friendly-nations-visum-panama-aufenthaltserlaubnis', permanent: true },
      { source: '/de/dienstleistungen/qualifizierter-investor-visum-panama',      destination: '/de/dienstleistungen/qualifizierter-investor-aufenthaltserlaubnis-panama', permanent: true },
      { source: '/de/dienstleistungen/einkommensteuer-panama',                    destination: '/de/dienstleistungen/einkommensteuererklarung-panama-expats',            permanent: true },
      { source: '/de/dienstleistungen/immobilien-kaufen-panama',                  destination: '/de/dienstleistungen/immobilien-kaufen-panama-auslaender',               permanent: true },
      { source: '/de/dienstleistungen/bankkonto-panama',                          destination: '/de/dienstleistungen/bankkonto-panama-auslaender-eroeffnen',             permanent: true },
      { source: '/de/dienstleistungen/unternehmen-gruenden-panama',               destination: '/de/dienstleistungen/unternehmen-gruenden-panama-auslaender',            permanent: true },
      { source: '/de/dienstleistungen/fuehrerschein-panama',                      destination: '/de/dienstleistungen/fuehrerschein-panama-auslaender',                   permanent: true },
      { source: '/de/dienstleistungen/versicherung-panama',                       destination: '/de/dienstleistungen/krankenversicherung-expats-panama',                 permanent: true },
      { source: '/de/warum-panama/lebensqualitaet-panama',                        destination: '/de/warum-panama/lebensqualitaet-kosten-panama',                        permanent: true },
      { source: '/de/warum-panama/gesundheitsversorgung-panama',                  destination: '/de/warum-panama/gesundheitskosten-expats-panama',                      permanent: true },
      { source: '/de/warum-panama/investitionen-panama',                          destination: '/de/warum-panama/investitionsmoeglichkeiten-panama',                    permanent: true },
      { source: '/de/warum-panama/finanzplatz-panama',                            destination: '/de/warum-panama/finanzplatz-banken-panama',                            permanent: true },
      { source: '/de/warum-panama/steuervorteile-panama',                         destination: '/de/warum-panama/territoriales-steuersystem-panama',                    permanent: true },

      // ─── Old sitemap wrong base paths (wildcard catches) ───────────────────
      { source: '/es/services/:slug*',   destination: '/es/servicios/:slug*',    permanent: true },
      { source: '/pt/services/:slug*',   destination: '/pt/servicos/:slug*',     permanent: true },
      { source: '/es/why-panama/:slug*', destination: '/es/por-que-panama/:slug*', permanent: true },
      { source: '/pt/why-panama/:slug*', destination: '/pt/por-que-panama/:slug*', permanent: true },
      { source: '/fr/why-panama/:slug*', destination: '/fr/pourquoi-panama/:slug*', permanent: true },

      // ─── Old static page redirects ──────────────────────────────────────────
      { source: '/es/services',   destination: '/es/servicios',                       permanent: true },
      { source: '/pt/services',   destination: '/pt/servicos',                        permanent: true },
      { source: '/es/why-panama', destination: '/es/por-que-panama',                  permanent: true },
      { source: '/pt/why-panama', destination: '/pt/por-que-panama',                  permanent: true },
      { source: '/fr/why-panama', destination: '/fr/pourquoi-s-installer-au-panama',  permanent: true },
      { source: '/es/contact',    destination: '/es/contacto',                        permanent: true },
      { source: '/pt/contact',    destination: '/pt/contato',                         permanent: true },
    ];
  },
};

export default withNextIntl(nextConfig);
